### ISSUE TITLE
tests/helpers.py is missing in the tarball on https://pypi.org/project/mrcfile/#files

### ISSUE THREAD

**Issue by yurivict** [ccpem/mrcfile#64]

**Comment by colinpalmer** [comment]
You're going to have to give me a bit more context for this one!

The test code is not distributed in the packages on pypi. What are you doing where it's a problem that `tests/helpers.py` is missing?

**Comment by yurivict** [comment]
The tests directory is present in the PYPI tarball, but helpers.py is missing.
This makes tests broken.

**Comment by colinpalmer** [comment]
Thanks. I wasn't aware that any test code was included in the tarball. I've now added the missing files so the full tests and docs will be included in future versions. I don't think it's worth making a new release just to include this, though, so for now, if you need a complete tarball, please use the one from the github release instead of the one from pypi.
